version: '3.8'
name: celery-app

services:
  redis:
    image: redis:7.0.11-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  celery:
    container_name: worker
    build:
      context: ./app
    command: celery --app=main worker -l INFO
    volumes:
      - ./app:/usr/src/app/
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0